# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_auto_20170309_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=50, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Customer', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.Item', verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.IntegerField(verbose_name='Transaction ID'),
        ),
    ]
