# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_auto_20170311_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
