# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_customer_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
