# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_auto_20170311_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
