# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_customer_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
