# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0011_auto_20170311_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stocks',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Subscribed'),
        ),
    ]
