# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_auto_20170313_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email_id',
            field=models.EmailField(default='', max_length=100, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
