# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0013_auto_20170314_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
