# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0013_auto_20170314_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('left_item1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_item1', to='AdminPanel.Item', verbose_name='Item')),
                ('left_item2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_item2', to='AdminPanel.Item', verbose_name='Item')),
                ('right_item1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_item1', to='AdminPanel.Item', verbose_name='Item')),
                ('right_item2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_item2', to='AdminPanel.Item', verbose_name='Item')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.IntegerField(default=1, verbose_name='Transaction ID'),
        ),
    ]
