# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0016_auto_20170329_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='left_item1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_item1', to='AdminPanel.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='left_item2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_item2', to='AdminPanel.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='right_item1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_item1', to='AdminPanel.Item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='right_item2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_item2', to='AdminPanel.Item', verbose_name='Item'),
        ),
    ]
