# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0018_auto_20170329_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='confidence',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='discount',
            name='left_item1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_item1', to='AdminPanel.Item', verbose_name='Left Item 1'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='left_item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_item2', to='AdminPanel.Item', verbose_name='Left Item 2'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='right_item1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_item1', to='AdminPanel.Item', verbose_name='Right Item 1'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='right_item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_item2', to='AdminPanel.Item', verbose_name='Right Item 2'),
        ),
    ]
