# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0020_auto_20170329_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_scanned', models.BigIntegerField(default=1)),
            ],
        ),
    ]
