# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0021_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Statistics',
        ),
    ]
