# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0022_auto_20170330_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
