# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0023_auto_20170330_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='run_time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
