# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0030_auto_20170423_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='server_ip_addrress',
            new_name='server_ip_address',
        ),
    ]
