# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0032_configuration_local_minimum_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='local_minimum_support',
            field=models.FloatField(),
        ),
    ]
