# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0033_auto_20170424_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='local_confidence',
            field=models.FloatField(default=80),
            preserve_default=False,
        ),
    ]
